[pytest]
testpaths = tests
addopts = -ra -p no:cacheprovider
cache_dir = .tmp/.pytest_cache
filterwarnings =
    ignore::DeprecationWarning:pydantic.*
    ignore::PendingDeprecationWarning:starlette.formparsers
