[pytest]
testpaths = microservicioProductos/tests
pythonpath = microservicioProductos
addopts = -ra -p no:cacheprovider
cache_dir = .tmp/.pytest_cache
filterwarnings =
    ignore::DeprecationWarning:pydantic.*
    ignore::PendingDeprecationWarning:starlette.formparsers
